//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecruise.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public long BookingId { get; set; }
        public long CustomerId { get; set; }
        public Nullable<long> TripId { get; set; }
        public long InvoiceId { get; set; }
        public double BookedPositionLatitude { get; set; }
        public double BookedPositionLongitude { get; set; }
        public System.DateTime BookingDate { get; set; }
        public Nullable<System.DateTime> PlannedDate { get; set; }
    
        public virtual Customer customer { get; set; }
        public virtual Trip trip { get; set; }
        public virtual Invoice invoice { get; set; }
    }
}
