//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecruise.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.car_charging_station = new HashSet<CarChargingStation>();
            this.car_maintenance = new HashSet<CarMaintenance>();
            this.trip = new HashSet<Trip>();
        }
    
        public long CarId { get; set; }
        public string LicensePlate { get; set; }
        public string ChargingState { get; set; }
        public string BookingState { get; set; }
        public long Milage { get; set; }
        public long MileageTotal { get; set; }
        public long Kilowatts { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public short YearOfConstruction { get; set; }
        public Nullable<double> LastKnownPositionLatitude { get; set; }
        public Nullable<double> LastKnownPositionLongitude { get; set; }
        public Nullable<System.DateTime> LastKnownPositionDate { get; set; }
        public double ChargeLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarChargingStation> car_charging_station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarMaintenance> car_maintenance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trip> trip { get; set; }
    }
}
