//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecruise.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarChargingStation
    {
        public long CarChargingStationId { get; set; }
        public long CarId { get; set; }
        public long ChargingStationId { get; set; }
        public System.DateTime ChargeStart { get; set; }
        public Nullable<System.DateTime> ChargeEnd { get; set; }
    
        public virtual Car car { get; set; }
        public virtual ChargingStation charging_station { get; set; }
    }
}
