//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecruise.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarMaintenance
    {
        public long CarMaintenanceId { get; set; }
        public long CarId { get; set; }
        public long MaintenanceId { get; set; }
        public long InvoiceItemId { get; set; }
        public Nullable<System.DateTime> PlannedDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
    
        public virtual Car car { get; set; }
        public virtual Maintenance maintenance { get; set; }
        public virtual InvoiceItem invoice_item { get; set; }
    }
}
