//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecruise.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerToken
    {
        public long TokenId { get; set; }
        public long CustomerId { get; set; }
        public string Type { get; set; }
        public string Token { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    
        public virtual Customer customer { get; set; }
    }
}
