//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecruise.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecruiseEntities : DbContext
    {
        public ecruiseEntities()
            : base("name=ecruiseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> booking { get; set; }
        public virtual DbSet<Car> car { get; set; }
        public virtual DbSet<CarChargingStation> car_charging_station { get; set; }
        public virtual DbSet<CarMaintenance> car_maintenance { get; set; }
        public virtual DbSet<ChargingStation> charging_station { get; set; }
        public virtual DbSet<Configuration> configuration { get; set; }
        public virtual DbSet<Customer> customer { get; set; }
        public virtual DbSet<CustomerToken> customer_token { get; set; }
        public virtual DbSet<Invoice> invoice { get; set; }
        public virtual DbSet<InvoiceItem> invoice_item { get; set; }
        public virtual DbSet<Maintenance> maintenance { get; set; }
        public virtual DbSet<Statistic> statistic { get; set; }
        public virtual DbSet<Trip> trip { get; set; }
    }
}
