//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecruise.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.booking = new HashSet<Booking>();
        }
    
        public long TripId { get; set; }
        public Nullable<long> CarId { get; set; }
        public long CustomerId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public double StartPositionLatitude { get; set; }
        public double StartPositionLongitude { get; set; }
        public Nullable<double> EndPositionLatitude { get; set; }
        public Nullable<double> EndPositionLongitude { get; set; }
        public double DistanceTravelled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> booking { get; set; }
        public virtual Car car { get; set; }
    }
}
